//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer(int id, String name, String email, String phoneNumber)
       {
           this.Reservations = new HashSet<Reservation>();
            this.id_customer = id;
            this.name=name;
            this.email = email;
            this.phone_number = phone_number;
        }

        public Customer() { }

        public int id_customer { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
    
       [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
       public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
