//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int flight_number { get; set; }
        public Nullable<int> source_airport { get; set; }
        public Nullable<int> destination_airport { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<System.DateTime> flight_time { get; set; }
        public string company_name { get; set; }

        public Airport Airport { get; set; }

        public Flight(int flight_number, Nullable<int> source_airport, Nullable<int> destination_airport, Nullable<int> price, Nullable<int> duration, Nullable<System.DateTime> flight_time,String company_name) {

            this.flight_number = flight_number;
            this.source_airport = source_airport;
            this.destination_airport = destination_airport;
            this.price = price;
            this.duration = duration;
            this.flight_time = flight_time;
            this.company_name = company_name;
        }
    
    }
}
