//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int id_reservation { get; set; }
        public Nullable<int> flight { get; set; }
        public Nullable<int> customer { get; set; }
        public string seat_number { get; set; }

        public Customer Customer1 { get; set; }
    
    }
}
